Hw11
onehundredtwenty-ninth/niffler-st4 pull request #14
Opened 2024-02-21 21:18 UTC by onehundredtwenty-ninth

2024-02-23 19:02 UTC, sashkir7 requested changes
Необходимо внести ряд правок

2024-02-23 19:02 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/test/SpendingTest.java
> +        ),
Можно создать какой-нибудь helper-класс со static-методом, который будет принимать дату в виде строки и возвращать объект типа Date

2024-02-23 19:02 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/test/SpendingTest.java
> +    new MainPage()
Как вариант, чтобы каждый раз не создавать экземпляры PageObject-классов, можно создать их на уровне базового тестового класса. И в самих тестовых классах использовать именно их

2024-02-23 19:02 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/condition/SpendCollectionConditionStudent.java
> +          for (SpendJson expectedSpend : expectedSpends) {
Почему реализация алгоритма - цикл в цикле? 
Это неверно - попробуйте реализовать проверку нескольких трат (то есть передавать 2 и более параметров). Каждый web-элемент будет сравниваться с каждым spendng-элементом, что неверно.
i-й web-элемент должен сравниваться с i-м spend-элементом. То есть цикл должен быть один.

2024-02-23 19:02 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/condition/SpendCollectionConditionStudent.java
> +          List<Boolean> checks = new ArrayList<>();
А нужно ли данные о том, пройдена проверка или нет, хранить в коллекции? Обычного boolean не хватит?

2024-02-23 19:02 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/condition/SpendCollectionConditionStudent.java
> +            checks.add(spendFromUi.equals(expectedSpend));
А если в expectedSpend будет заполнено поле id (по идее, оно как раз-таки и должно быть заполненным). Например, создали траты через extension. 
Тогда проверка упадет, тк поле id будет разным (null != какой-то id)

2024-02-26 08:47 UTC, sashkir7 approved these changes

2024-02-26 08:47 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/condition/SpendCollectionConditionStudent.java
> +        }
Можно ведь просто isCheckSuccess = большая проверка
И чтобы каждый раз не писать expectedSpends[i] - можно шагом выше вынести в переменную

2024-02-26 09:28 UTC, onehundredtwenty-ninth commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/condition/SpendCollectionConditionStudent.java
> +        }
Если просто isCheckSuccess = большая проверка, то мы можем перезаписать неуспешный результат проверки предыдущего элемента, и получить ложно-положительный результат

2024-02-26 09:29 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/condition/SpendCollectionConditionStudent.java
> +        }
Ага, в точку - из головы вылетело

2024-02-26 13:54 UTC, merged