Hw14
onehundredtwenty-ninth/niffler-st4 pull request #18
Opened 2024-02-24 13:20 UTC by onehundredtwenty-ninth

2024-02-26 20:48 UTC, sashkir7 requested changes
Есть небольшой момент относительно логики ApiLoginExtension
Более детально отписался в комментрии. Крайне желательно поправить

2024-02-26 20:48 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/api/interceptor/CodeInterceptorStudent.java
> +public class CodeInterceptorStudent implements Interceptor {
Как правило, Interceptor указывают в конце
То есть CodeStudentInterceptor

2024-02-26 20:48 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/jupiter/extension/ApiLoginExtension.java
> +        var userAuth = extensionContext.getStore(DbUserExtension.NAMESPACE)
Поле аннотации не может быть равным null
То есть в данное условие мы будем попадать каждый первый раз

Советую реализовать след. образом:
1. В аннотацию DBUser добавить boolean-поле, например, handle. По умолчанию оно равно true.
2. В аннотации ApiLogin поле user по умолчанию равно @DBUser(handle = false). 
3. На основании этого поля (handle) можно выстраивать различную логику в наших extension(ах)

PS. Поле аннотации не может быть равным null. Попробуйте передать - java выдаст ошибку и программа не скомпилируется

2024-02-26 20:58 UTC, onehundredtwenty-ninth commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/jupiter/extension/ApiLoginExtension.java
> +        var userAuth = extensionContext.getStore(DbUserExtension.NAMESPACE)
Мы получаем аннотацию с помощью 
```
    ApiLogin apiLogin = AnnotationSupport.findAnnotation(
        extensionContext.getRequiredTestMethod(),
        ApiLogin.class
    ).orElse(null);
```
Она будет null если мы ее не найдем

2024-02-26 21:06 UTC, onehundredtwenty-ninth commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/jupiter/extension/ApiLoginExtension.java
> +        var userAuth = extensionContext.getStore(DbUserExtension.NAMESPACE)
А, все, понял, речь про поле

2024-02-27 19:50 UTC, sashkir7 approved these changes

2024-02-27 21:38 UTC, merged