Hw7
onehundredtwenty-ninth/niffler-st4 pull request #6
Opened 2024-02-11 20:03 UTC by onehundredtwenty-ninth

2024-02-12 11:26 UTC, sashkir7 requested changes
Необходимо доработать работу с БД
Более детально - см комментарии

2024-02-12 11:26 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +    return null;
Не нужно возвращать null
Нужно объявить и вернуть entity не в условии if

```
      try (var rs = ps.executeQuery()) {
        var user = new UserEntity();
        if (rs.next()) {
          user.setId(id);
          user.setUsername(rs.getString("username"));
          user.setCurrency(CurrencyValues.valueOf(rs.getString("currency")));
          user.setFirstname(rs.getString("firstname"));
          user.setSurname(rs.getString("surname"));
          user.setPhoto(rs.getBytes("photo"));
        }
        return user;
      }
```

2024-02-12 11:26 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +    return null;
Так делать не нужно - см. коммент ниже

2024-02-12 11:26 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +  }
Хорошо бы доработать, чтобы можно было обновлять права
Для этого, например, можно сначала удалить все права для данного пользователя. А после - вставить

2024-02-12 11:26 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
>    }
А где finally с con.setAutoCommit(true);

2024-02-12 11:26 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +      var faker = new Faker();
Можно объявить на уровне класса

2024-02-12 11:26 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +      context.getStore(NAMESPACE).put(context.getUniqueId() + "-user", user);
Логика формирования ключа много где используется. А если она поменяется? 
Где-нибудь, скорее всего, забудете изменить - и будет непонятное поведение...
Рекомендую вынести логику формирования ключа в отдельные методы - чтобы логика была в единственном месте

2024-02-12 13:56 UTC, onehundredtwenty-ninth commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +    return null;
Не кажется это оптимальным решением в силу того, что запись с переданным id может и отсутсвовать. С моей реализацией вернется null и можно будет это в месте вызова метода проверить и обработать. С предложенной тобой релизацией у нас вернется пустой объект UserEntity, в чем бенефиты?

2024-02-12 13:59 UTC, onehundredtwenty-ninth commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +    return null;
Если глянуть на тот же Hebernate, то он при отсутствии сущности тоже вернет null, так и моя реализация

2024-02-12 20:31 UTC, onehundredtwenty-ninth commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +    return null;
Отписал в комменте ниже

2024-02-13 02:25 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +    return null;
Доброе утро!
Да, в ваших словах есть доля правды. Соглашусь - такая реализация будет более наглядной и интуитивно понятной.

2024-02-13 02:27 UTC, sashkir7 commented on niffler-e-2-e-tests-student/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +  }
Как вариант - можно передавать context - и uniqueId получать здесь (чтобы каждый раз при вызове не писать context.getUniqueId())

2024-02-13 02:28 UTC, sashkir7 approved these changes
Правки посмотрел - все круто, зачет!
Отдельный респект за то, что можете отстоять свое мнение и решение - это очень здорово! По поводу того, чтобы вернуть null - решение здравое, согласен

2024-02-13 06:06 UTC, merged